### ISSUE TITLE
Incorrect instructions on install / usage

### ISSUE THREAD

**Issue by petercn** [derekstavis/touchrunner#1]
Derek, thanks for the cool work on this, however, I found an issue which I was able to self-resolve.

Your current usage instructions say to "omf install npm-touchbar", however, the correct name of your plugin under the omf directory is "touchrunner" and therefore the command for installing the plugin should be "omf install touchrunner".

Also, I'd recommend you specify that "oh my fish" is a dependency which itself has a dependency on fish shell.

To get this working from scratch, I did:

brew install fish
curl -L https://get.oh-my.fish | fish
omf install touchrunner

**Comment by derekstavis** [comment]
Solved in aaaa3ea, thanks for the report!
